In [196]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [197]:
df = pd.read_csv("tweets.csv")
df.head()

likes  retweets  replies  is_viral
0     10         2        0         0
1    123        14        5         1
2    203        34       29         1
3     23         2        3         0
4      1         0        0         0

In [198]:
df.shape

(100, 4)

In [199]:
df['is_viral'].value_counts()

is_viral
0    74
1    26
Name: count, dtype: int64

In [200]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [201]:
x[0:5]

array([[ 10,   2,   0],
       [123,  14,   5],
       [203,  34,  29],
       [ 23,   2,   3],
       [  1,   0,   0]])

In [202]:
y[0:5]

array([0, 1, 1, 0, 0])

In [203]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
x_train.shape

(80, 3)

In [204]:
clf = RandomForestClassifier()
clf.fit(x_train, y_train)

RandomForestClassifier()

In [205]:
viral_predict = clf.predict([[5, 5, 5], [199, 20, 1]])
viral_predict

array([0, 1])

In [206]:
y_pred = clf.predict(x_test)

In [207]:
x_test

array([[ 29,   2,   2],
       [ 65,   4,   2],
       [203,  34,  29],
       [ 28,   0,  10],
       [ 33,   3,   3],
       [ 50,   5,   5],
       [  0,   0,  11],
       [  0,   0,   5],
       [ 39,   3,   9],
       [ 48,   3,  20],
       [ 15,   2,   0],
       [  1,   0,   4],
       [ 34,   1,   1],
       [ 52,  10,   1],
       [ 38,   4,   4],
       [144,  20,   8],
       [  9,   1,   1],
       [167,  22,  10],
       [ 11,   2,   4],
       [298,  38,  32]])

In [208]:
y_test

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1])

In [209]:
y_pred

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1])

In [210]:
accuracy_score(y_test, y_pred)

1.0

In [222]:
df_compare = pd.DataFrame(
    data={
        'likes': x_test[:,0],
        'retweets': x_test[:,1],
        'replies': x_test[:,2],
        'predicted_value': y_pred, 
        'real_value': y_test
    }, 
    columns=['likes', 'retweets', 'replies', 'predicted_value', 'real_value'])
df_compare

likes  retweets  replies  predicted_value  real_value
0      29         2        2                0           0
1      65         4        2                0           0
2     203        34       29                1           1
3      28         0       10                0           0
4      33         3        3                0           0
5      50         5        5                0           0
6       0         0       11                0           0
7       0         0        5                0           0
8      39         3        9                0           0
9      48         3       20                0           0
10     15         2        0                0           0
11      1         0        4                0           0
12     34         1        1                0           0
13     52        10        1                0           0
14     38         4        4                0           0
15    144        20        8                1           1
16      9         1        1                0           0
17    167        22       10                1           1
18     11         2        4                0           0
19    298        38       32                1           1